" Custom Vim Functions
command -complete=custom,GetChecklists -nargs=1 Checklists call Checklists(<f-args>)
fun GetChecklists(A,L,P)
	if has("win32") || has("win64")
		return system('dir /B /A-D ' . expand($HOME) . '\vimfiles\checklists\')
	else
		return system('ls -1 ' . expand($HOME) . '/.vim/checklists/')
	endif
endfunction

function Checklists(file)
	echo a:file
	if has("win32") || has("win64")
		execute 'r' expand($HOME) . '\vimfiles\checklists\' . a:file
	else
		execute 'r' expand($HOME) . '/.vim/checklists/' . a:file
	endif
endfunction

command -complete=custom,GetSkeletons -nargs=1 Skeletons call Skeletons(<f-args>)
fun GetSkeletons(A,L,P)
	if has("win32") || has("win64")
		return system('dir /B /A-D ' . expand($HOME) . '\vimfiles\skeletons\')
	else
		return system('ls -1 ' . expand($HOME) . '/.vim/skeletons/')
	endif
endfunction

function Skeletons(file)
	echo a:file
	if has("win32") || has("win64")
		execute 'r' expand($HOME) . '\vimfiles\skeletons\' . a:file
	else
		execute 'r' expand($HOME) . '/.vim/skeletons/' . a:file
	endif
endfunction

command MdTags :call MdTags()
function! MdTags()
        " 1. Perform search
        :vimgrep /\*.\{-}\*/j **/*.md

        let l:tags = []
        " 2. Loop through matches
        for item in getqflist()
                call add(l:tags, substitute(item.text, '\*', '', 'g') . "\t" . bufname(item.bufnr) . "\t\/" . item.text)
        endfor

        " tags files are considered invalid if not sorted!
        call sort(l:tags)
        call writefile(l:tags, 'tags', '')
        echo "created tags file"
endfunction

fun s:_ValidateTable(selection)
    let l:selection = a:selection

    let l:i = 0
    let l:cols = 0
    while l:i < len(l:selection)
        let l:selection[l:i] = substitute(l:selection[l:i], '.\{-}\(|\)', '\1', '')
        let l:selection[l:i] = substitute(l:selection[l:i], '\s\+', '', 'g')

        " Handle header row
        if l:i == 1
            if l:selection[l:i] =~? '^[|-]\+$'
                let l:i += 1
                continue
            else
                echo "Invalid header divider"
                return []
            endif
        else
            let l:selection[l:i] = split(l:selection[l:i], '|')
        endif

        if l:i == 0
            let l:cols = len(l:selection[l:i])
        elseif len(l:selection[l:i]) != l:cols
            echo "Error in number of columns on line " . (l:i+1)
            return []
        endif

        let l:i += 1

    endwhile

    " Remove header row
    unlet l:selection[1]

    return l:selection
endfunction

fun s:_GetColWidths(rows)
    let l:lengths = []
    let l:rows = a:rows

    let l:i = 0
    while l:i < len(l:rows)

        let l:col_num = 0
        for col in l:rows[l:i]
            if l:i == 0
                call add(l:lengths, len(col))
            else
                if len(col) > l:lengths[l:col_num]
                    let l:lengths[l:col_num] = len(col)
                endif
            endif

            let l:col_num += 1
        endfor

        let l:i += 1
    endwhile

    return l:lengths
endfunction

fun s:_BuildTable(rows, widths)
    let l:rows = a:rows

    let l:r = 0
    while l:r < len(l:rows)

        let l:c = 0
        while l:c < len(l:rows[l:r])
            let l:rows[l:r][l:c] = printf(' %-*s ', a:widths[l:c], l:rows[l:r][l:c])
            let l:c += 1
        endwhile

        let l:rows[l:r] = '|' . join(l:rows[l:r], '|') . '|'

        let l:r += 1
    endwhile

    let l:div = '|'
    let l:i = 0
    while l:i < len(a:widths)
        let l:div = l:div . ' ' . repeat('-',a:widths[l:i]) . ' |'
        let l:i += 1
    endwhile

    call insert(l:rows, l:div, 1)
    " TODO make rows one string
    let l:table = join(l:rows, '\n')

    return l:table
endfunction

fun FormatTable() range
    let l:selection = getline("'<", "'>")

    " Ensure table is valid and divider removed
    let l:rows = s:_ValidateTable(l:selection)
    if len(l:rows) == 0
        return
    endif

    " Get the width of each column
    let l:widths = s:_GetColWidths(l:rows)

    let l:table = s:_BuildTable(l:rows, l:widths)

    echo l:table
endfunction

" Global keymaps
let mapleader = " "

" Checkbox commands
nnoremap <leader>cc :normal! 0t]rx<Esc>
nnoremap <leader>cu :normal! 0t]r<Space><Esc>

" Use a block cursor for all modes
set guicursor=n-v-c-i:block
" Allows dashes in tags
set iskeyword+=-
" Turn on line numbers
set number
" Less cowbell
set belloff=all
" Don't leave visual mode when indenting
vnoremap > >gv
vnoremap < <gv
" Set tabs and shiftwidth to 4 spaces
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4
" Tunn on syntax highlighting
syntax on

" Disable mouse
set mouse=
" Render speical characters
set nolist

" Searching
"" Highlight as you type
set incsearch
"" Highlight all matches
set hlsearch

" Statusline
"" Always show the statusline
set laststatus=2
hi StatusLine cterm=bold ctermbg=DarkGrey ctermfg=White

" Shadow Files
"" No undo files
set noundofile
"" Remove backup files after they have been saved
set nobackup
set nowritebackup

" Spelling
"" MarkDown
autocmd FileType markdown setlocal spell

" Plugins
"" Load all plugins
"packloadall

" vim-table-mode
"let g:table_mode_corner='|'
