" Custom Vim Functions
command -complete=custom,GetChecklists -nargs=1 Checklists call Checklists(<f-args>)
fun GetChecklists(A,L,P)
	if has("win32") || has("win64")
		return system('dir /B /A-D ' . expand($HOME) . '\vimfiles\checklists\')
	else
		return system('ls -1 ' . expand($HOME) . '\.vim\checklists\')
	endif
endfunction

function Checklists(file)
	echo a:file
	if has("win32") || has("win64")
		execute 'r' expand($HOME) . '\vimfiles\checklists\' . a:file
	else
		execute 'r' expand($HOME) . '\.vim\checklists\' . a:file
	endif
endfunction

command -complete=custom,GetSkeletons -nargs=1 Skeletons call Skeletons(<f-args>)
fun GetSkeletons(A,L,P)
	if has("win32") || has("win64")
		return system('dir /B /A-D ' . expand($HOME) . '\vimfiles\skeletons\')
	else
		return system('ls -1 ' . expand($HOME) . '\.vim\skeletons\')
	endif
endfunction

function Skeletons(file)
	echo a:file
	if has("win32") || has("win64")
		execute 'r' expand($HOME) . '\vimfiles\skeletons\' . a:file
	else
		execute 'r' expand($HOME) . '\.vim\skeletons\' . a:file
	endif
endfunction

" Global keymaps
let mapleader = " "

" Checkbox commands
nnoremap <leader>cc :normal! 0t]rx<Esc>
nnoremap <leader>cu :normal! 0t]r<Space><Esc>

" Use a block cursor for all modes
set guicursor=n-v-c-i:block
" Allows dashes in tags
set iskeyword+=-
" Turn on line numbers
set number
" Less cowbell
set belloff=all
" Don't leave visual mode when indenting
vnoremap > >gv
vnoremap < <gv
" Set tabs and shiftwidth to 4 spaces
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4
" Tunn on syntax highlighting
syntax on

" Disable mouse
set mouse=

" Searching
"" Highlight as you type
set incsearch
"" Highlight all matches
set hlsearch

" Statusline
"" Always show the statusline
set laststatus=2
hi StatusLine cterm=bold ctermbg=DarkGrey ctermfg=White

" Shadow Files
"" No undo files
set noundofile
"" Remove backup files after they have been saved
set nobackup
set nowritebackup

" Spelling
"" MarkDown
autocmd FileType markdown setlocal spell

" Plugins
"" Load all plugins
"packloadall

" vim-table-mode
"let g:table_mode_corner='|'
